# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-27 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharespot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='main_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticketimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='TicketImg/%Y/%m/%d'),
        ),
    ]
