# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-04 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharespot', '0002_auto_20180727_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareinfocomment',
            name='anony_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
